export const DEFAULT_PRODUCT = {
    name: "",
    price: 0,
    description: "",
    isReduced: false,
    reducedPrice: 0,
    isDiscountProcentual: false,
    allergens: [] as string[],
    image: null as null | string,
    nutritionalValues: "",
}

export const ALLERGENS = [
    "Gluten",
    "Crustaceans",
    "Eggs",
    "Fish",
    "Peanuts",
    "Soybeans",
    "Milk",
    "Nuts",
    "Celery",
    "Mustard",
    "Sesame",
    "Sulfur dioxide",
    "Lupin",
    "Molluscs",
]

export const RO_ALLERGENS = [
    "Gluten",
    "Crustacee",
    "Ouă",
    "Pește",
    "Arahide",
    "Soia",
    "Lapte",
    "Nuci",
    "Țelină",
    "Muștar",
    "Semințe de susan",
    "Dioxid de sulf",
    "Lupin",
    "Moluște",
];